<a href="https://colab.research.google.com/github/sgtlee99/PythonTEST/blob/main/%ED%8C%8C%EC%9D%B4%EC%8D%AC_9%EC%9D%BC%EC%B0%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#넘파이 배열 생성
import numpy as np

arr = np.array([1,2,3]) #넘파이 배열(리스트)
print(arr)              #넘파이 배열 출력 => 구분자 빈칸
print(type(arr))        #넘파이 배열 타입 = ndarray

[1 2 3]
<class 'numpy.ndarray'>


shape -> 배열의 형태 : 튜플로 표현

In [2]:
#넘파이 배열의 속성(필드)
import numpy as np

arr1 = np.array([1,2,3])
print(arr1)
print(arr1.ndim, arr1.shape, arr1.dtype, arr1.itemsize, arr1.size)

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2.ndim, arr2.shape, arr2.dtype, arr2.itemsize, arr2.size)

arr3 = np.array([[[1,1,1], [2,2,2]], [[3,3,3],[4,4,4]]])
print(arr3)
print(arr3.ndim, arr3.shape, arr3.dtype, arr3.itemsize, arr3.size)

[1 2 3]
1 (3,) int64 8 3
[[1 2 3]
 [4 5 6]]
2 (2, 3) int64 8 6
[[[1 1 1]
  [2 2 2]]

 [[3 3 3]
  [4 4 4]]]
3 (2, 2, 3) int64 8 12


In [7]:
#넘파이 배열의 연산 : 브로드 캐스팅
#리스트와 넘파이 배열 + 연산의 차이
import numpy as np

arr1 = np.array([1,2,3])
arr1 = arr1 + 2
print(arr1)               #넘파이 배열 +2 연산

arr1 = arr1 ** 2
print(arr1)               #넘파이 배열 **2 연산

lst1 = [1,2,3]
lst2 = [4,5,6]
print(lst1 + lst2)        #리스트 + 리스트 ==> 연결

arr2 = np.array([1,2,3])
arr3 = np.array([4,5,6])
print(arr2 + arr3)        #넘파이배열 + 넘파이배열 ==> 원소별 덧셈

[3 4 5]
[ 9 16 25]
[1, 2, 3, 4, 5, 6]
[5 7 9]


In [10]:
#넘파이 배열 곱셈 연산자 : * 와 @
import numpy as np

arr1 = np.array([[1,1],[2,2]])
arr2 = np.array([[1,2], [3,4]])

arr3 = arr1 * arr2            #넘파이배열 * 연산자 => 원소별 곱셈
print(arr3)

arr4 = arr1 @ arr2            #넘파이배열 @ 연산자 => 행렬 곱셈
print(arr4)

[[1 2]
 [6 8]]
[[ 4  6]
 [ 8 12]]


In [11]:
#실습. BMI계산
import numpy as np

h = [1.83, 1.75, 1.17, 1.85, 1.77, 1.73]
w = [80, 74, 59, 90, 77, 78]

harr = np.array(h)
warr = np.array(w)

bmi = warr / harr ** 2
print(bmi)

[23.88844098 24.16326531 43.10029951 26.29656684 24.57786715 26.06167931]


In [12]:
#인덱싱과 슬라이싱
import numpy as np

arr = np.array([1,2,3,4,5])
n = arr.size

print(arr[0])
print(arr[-1], arr[n-1])

print(arr[1:4])
print(arr[0:-1], arr[0:4])
print(arr[:], arr[0:], arr[:n], arr[0:n])

1
5 5
[2 3 4]
[1 2 3 4] [1 2 3 4]
[1 2 3 4 5] [1 2 3 4 5] [1 2 3 4 5] [1 2 3 4 5]


In [16]:
#2차원 배열 인덱싱, 슬라이싱
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])
print(arr[0])
print(arr[0][1], arr[0,1])
print(arr[-1][-1], arr[-1,-1])

arr[0,0] = 7.7   #arr는 정수형태로 생성
print(arr)        #실수 입력시 타입변환

print(arr[0, :])  #1차원
print(arr[0:1, :])#2차원
print(arr[0, ::2])#step => 2 

[1 2 3]
2 2
6 6
[[7 2 3]
 [4 5 6]]
[7 2 3]
[[7 2 3]]
[7 3]


In [18]:
#2차원 배열 논리 인덱싱
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])

larr = arr[:, 0] % 2 == 0
print(arr[:,0], larr)

print(arr[larr])

[1 4] [False  True]
[[4 5 6]]


In [19]:
#실습. 2차원 배열에서 조건 만족 행 추출
import numpy as np
lst = [
    [177, 77.1],
    [183, 80.1],
    [185, 78.3],
    [173, 80.3]
]
arr = np.array(lst)
print("몸무게가 80 이상")
print(arr[  arr[:, 1] >= 80.0])

print("키가 180이상")
print(arr[arr[:,0] >= 180.0])

몸무게가 80 이상
[[183.   80.1]
 [173.   80.3]]
키가 180이상
[[183.   80.1]
 [185.   78.3]]


In [27]:
#넘파이 배열생성/초기화
import numpy as np
print(np.zeros((3,4)))    #3행, 4열 배열생성 -> 0 초기화
print(np.ones((3,4)))     #3행, 4열 배열생성 -> 1 초기화
print(np.eye(3))          #3행3열 단위 행렬 생성, 대각 원소 1, 나머지 0 초기화

print("==================")
print(np.arange(10), np.array(range(10)))         #크기 10 배열 0~9 초기화
print(np.arange(1,10), np.array(range(1,10)))     #크기 9 배열 1~9 초기화
print(np.arange(0,10,2), np.array(range(0,10,2))) #크기 5 배열 0~8 짝수 초기화
print("==================")
print(np.linspace(1,10,10))   
#np.linspace(start, stop, num = 50)
#크기가 num인 실수배열, start~stop까지 균등한 간격의 num개 실수 초기화
print(np.logspace(0,1,10))
#np.logspace(startm stop, num=50)
#크기가 num인 실수배열, 10^start ~ 10^stop까지 로그스케일로 균등항 간격의 num개 실수 초기화

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 1 2 3 4 5 6 7 8 9] [0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9] [1 2 3 4 5 6 7 8 9]
[0 2 4 6 8] [0 2 4 6 8]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.          1.29154967  1.66810054  2.15443469  2.7825594   3.59381366
  4.64158883  5.9948425   7.74263683 10.        ]


In [28]:
#넘파이 배열 형태 변경
import numpy as np
arr1 = np.arange(8)   #크기가 8인 1차원 배열생성 -> 0~7 초기화
print(arr1, "\n")

arr2 = arr1.reshape(2,4)  #arr1 -> 2행 4열 2차원 배열로 변경
print(arr2, "\n")

print(arr2.flatten(), arr2.reshape(-1)) #arr2 -> 1차원 배열로 변경


[0 1 2 3 4 5 6 7] 

[[0 1 2 3]
 [4 5 6 7]] 

[0 1 2 3 4 5 6 7] [0 1 2 3 4 5 6 7]


In [31]:
#난수배열 생성
import numpy as np
np.random.seed(1)   #난수생성 초기값 설정
arr1 = np.random.rand(10)   #크기가 10인 1차원 난수배열 생성 0~1 사이 난수
print(10*arr1 + 10)   #브로드캐스팅 연산으로 10~20 사이 난수생성

arr2 = np.random.randint(1,11,size=(3,5))   #3행5열 난수, 1~10 사이 난수
print(arr2)

print(np.random.randint(1,6,size=10))   #크기10 1차원 난수배열 1~5사이 난수

[14.17022005 17.20324493 10.00114375 13.02332573 11.46755891 10.92338595
 11.86260211 13.45560727 13.96767474 15.38816734]
[[ 6  3  5  3  5]
 [ 8  8 10  2  8]
 [ 1  7 10 10  8]]
[2 2 1 5 2 1 1 4 3 2]


In [33]:
#정규분포 난수생성
import numpy as numpy

np.random.seed(1)
print(np.random.normal(0,1,5))  #평균0, 표준편차1 정규분포 난수 배열(크기 5)

np.random.seed(1)
print(np.random.randn(5))   #np.random.normal(0,1,5와 동일)
print()

np.random.seed(1)
print(np.random.normal(10,2,(2,5)))   #2행 5열 난수배열, 평균10, 표준편차2 난수
print()

np.random.seed(1)   
print(np.random.randn(2,5) * 2 + 10)

[ 1.62434536 -0.61175641 -0.52817175 -1.07296862  0.86540763]
[ 1.62434536 -0.61175641 -0.52817175 -1.07296862  0.86540763]

[[13.24869073  8.77648717  8.9436565   7.85406276 11.73081526]
 [ 5.39692261 13.48962353  8.4775862  10.63807819  9.50125925]]

[[13.24869073  8.77648717  8.9436565   7.85406276 11.73081526]
 [ 5.39692261 13.48962353  8.4775862  10.63807819  9.50125925]]


In [34]:
#난수관련 함수
import numpy as np

x = np.arange(1,11)
np.random.shuffle(x)    #원본배열 순서 랜덤 생성
print(x)

y = np.arange(1,11)
print(np.random.permutation(y))   #순서랜덤 변경 배열반환, 원본변경X
print(y)

fruits = ["apple", "banana", "cherries", "durian", "grapes", "lemon", "mango"]
pb = [0.1,0,0.2,0.5,0.1,0.05,0.05]    #표본 추출 확률 리스트
print(np.random.choice(fruits, 3, replace=False, p = pb))   #중복없이 랜덤추출

[ 9  4  6 10  1  7  2  8  5  3]
[ 3  5  4  1  7  2  6  9  8 10]
[ 1  2  3  4  5  6  7  8  9 10]
['apple' 'cherries' 'lemon']


In [36]:
#넘파이 배열 평균 계산
import numpy as numpy
arr = np.array([[99,93,60],[98,82,93],[93,65,81],[78,82,81]])
print(arr, "\n")

print(np.mean(arr, axis=0))
print(arr.mean(axis=0), '\n')

print(np.mean(arr, axis=1))
print(arr.mean(axis=1))

[[99 93 60]
 [98 82 93]
 [93 65 81]
 [78 82 81]] 

[92.   80.5  78.75]
[92.   80.5  78.75] 

[84.         91.         79.66666667 80.33333333]
[84.         91.         79.66666667 80.33333333]
